apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejs-app
  template:
    metadata:
      labels:
        app: ejs-app
    spec:
      containers:
      - name: ejs-app
        image: soheldev/my-ejs-app:latest
        ports:
        - containerPort: 3257
apiVersion: v1
kind: Service
metadata:
  name: ejs-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3257
  selector:
    app: ejs-app        
