apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejs-app-deployment
  namespace: ejs-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejs-app
  template:
    metadata:
      labels:
        app: ejs-app
    spec:
      containers:
      - name: ejs-app
        image: soheldev/my-ejs-app:latest
        ports:
        - containerPort: 3257
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: ejs-app-service
  namespace: ejs-app-service
spec:
  type: NodePort
  ports:
    - port: 3250
      targetPort: 3257
      nodePort: 32507
  selector:
    app: ejs-app
